title: My Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  A simple portfolio site.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://2ufkpfb9daxnik.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-toc